// Code generated by "stringer -type=Edge"; DO NOT EDIT.

package hooks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pre-1]
	_ = x[Callback-2]
	_ = x[Post-4]
}

const (
	_Edge_name_0 = "PreCallback"
	_Edge_name_1 = "Post"
)

var (
	_Edge_index_0 = [...]uint8{0, 3, 11}
)

func (i Edge) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Edge_name_0[_Edge_index_0[i]:_Edge_index_0[i+1]]
	case i == 4:
		return _Edge_name_1
	default:
		return "Edge(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
