version: 2
updates:
  # Docs use Python only for static site generation.
  - package-ecosystem: "pip"
    directory: /docs
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
