linters:
  enable:
  - goimports
  - revive

linters-settings:
  revive:
    rules:
      - name: time-equal
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    # Disable staticcheck 'Empty body in an if or else branch' as it's useful
    # to put a comment into an empty else-clause that explains why whatever
    # is done in the if-caluse is not necessary if the condition is false.
    - linters:
        - staticcheck
      text: "SA9003:"

