version: "2"
linters:
  enable:
    - revive
  settings:
    revive:
      rules:
        - name: time-equal
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - staticcheck
        text: 'SA9003:'
      - linters:
          - staticcheck
        text: '(QF1001|QF1011|ST1012|QF1008|ST1005|ST1023|QF1003|ST1006|ST1001|QF1004):'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/zrepl/zrepl
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
