// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package rpc

import "strconv"

const _DataType_name = "DataTypeNoneDataTypeControlDataTypeMarshaledJSONDataTypeOctets"

var _DataType_index = [...]uint8{0, 12, 27, 48, 62}

func (i DataType) String() string {
	i -= 1
	if i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
