// Code generated by "stringer -type=FSReplicationState"; DO NOT EDIT.

package fsfsm

import "strconv"

const (
	_FSReplicationState_name_0 = "FSReadyFSRetryWait"
	_FSReplicationState_name_1 = "FSPermanentError"
	_FSReplicationState_name_2 = "FSCompleted"
)

var (
	_FSReplicationState_index_0 = [...]uint8{0, 7, 18}
)

func (i FSReplicationState) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _FSReplicationState_name_0[_FSReplicationState_index_0[i]:_FSReplicationState_index_0[i+1]]
	case i == 4:
		return _FSReplicationState_name_1
	case i == 8:
		return _FSReplicationState_name_2
	default:
		return "FSReplicationState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
