// Code generated by "stringer -type=State"; DO NOT EDIT.

package replication

import "strconv"

const (
	_State_name_0 = "PlanningPlanningError"
	_State_name_1 = "Working"
	_State_name_2 = "WorkingWait"
	_State_name_3 = "Completed"
	_State_name_4 = "ContextDone"
)

var (
	_State_index_0 = [...]uint8{0, 8, 21}
)

func (i State) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _State_name_0[_State_index_0[i]:_State_index_0[i+1]]
	case i == 4:
		return _State_name_1
	case i == 8:
		return _State_name_2
	case i == 16:
		return _State_name_3
	case i == 32:
		return _State_name_4
	default:
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
