jobs:
  - type: push
    name: "push"
    filesystems: {
      "<": true,
      "tmp": false
    }
    connect:
      type: tcp
      address: "backup-server.foo.bar:8888"
    snapshotting:
      type: manual
    send:
      encrypted: false
    pruning:
      keep_sender:
        - type: not_replicated
        - type: last_n
          count: 10
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d
          regex: "^zrepl_.*"
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d
          regex: "^zrepl_.*"