// Code generated by "stringer -type=StepState"; DO NOT EDIT.

package fsrep

import "strconv"

const (
	_StepState_name_0 = "StepReplicationReadyStepReplicationRetry"
	_StepState_name_1 = "StepMarkReplicatedReady"
	_StepState_name_2 = "StepMarkReplicatedRetry"
	_StepState_name_3 = "StepPermanentError"
	_StepState_name_4 = "StepCompleted"
)

var (
	_StepState_index_0 = [...]uint8{0, 20, 40}
)

func (i StepState) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _StepState_name_0[_StepState_index_0[i]:_StepState_index_0[i+1]]
	case i == 4:
		return _StepState_name_1
	case i == 8:
		return _StepState_name_2
	case i == 16:
		return _StepState_name_3
	case i == 32:
		return _StepState_name_4
	default:
		return "StepState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
