// Code generated by "stringer -type=Conflict"; DO NOT EDIT.

package zfs

import "strconv"

const _Conflict_name = "ConflictIncrementalConflictAllRightConflictNoCommonAncestorConflictDiverged"

var _Conflict_index = [...]uint8{0, 19, 35, 59, 75}

func (i Conflict) String() string {
	if i < 0 || i >= Conflict(len(_Conflict_index)-1) {
		return "Conflict(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Conflict_name[_Conflict_index[i]:_Conflict_index[i+1]]
}
