// Code generated by "stringer -type=Conflict"; DO NOT EDIT.

package zfs

import "fmt"

const _Conflict_name = "ConflictIncrementalConflictAllRightConflictNoCommonAncestorConflictDiverged"

var _Conflict_index = [...]uint8{0, 19, 35, 59, 75}

func (i Conflict) String() string {
	if i < 0 || i >= Conflict(len(_Conflict_index)-1) {
		return fmt.Sprintf("Conflict(%d)", i)
	}
	return _Conflict_name[_Conflict_index[i]:_Conflict_index[i+1]]
}
