// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.0
// source: pdu.proto

package pdu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicationGuaranteeKind int32

const (
	ReplicationGuaranteeKind_GuaranteeInvalid                ReplicationGuaranteeKind = 0
	ReplicationGuaranteeKind_GuaranteeResumability           ReplicationGuaranteeKind = 1
	ReplicationGuaranteeKind_GuaranteeIncrementalReplication ReplicationGuaranteeKind = 2
	ReplicationGuaranteeKind_GuaranteeNothing                ReplicationGuaranteeKind = 3
)

// Enum value maps for ReplicationGuaranteeKind.
var (
	ReplicationGuaranteeKind_name = map[int32]string{
		0: "GuaranteeInvalid",
		1: "GuaranteeResumability",
		2: "GuaranteeIncrementalReplication",
		3: "GuaranteeNothing",
	}
	ReplicationGuaranteeKind_value = map[string]int32{
		"GuaranteeInvalid":                0,
		"GuaranteeResumability":           1,
		"GuaranteeIncrementalReplication": 2,
		"GuaranteeNothing":                3,
	}
)

func (x ReplicationGuaranteeKind) Enum() *ReplicationGuaranteeKind {
	p := new(ReplicationGuaranteeKind)
	*p = x
	return p
}

func (x ReplicationGuaranteeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicationGuaranteeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pdu_proto_enumTypes[0].Descriptor()
}

func (ReplicationGuaranteeKind) Type() protoreflect.EnumType {
	return &file_pdu_proto_enumTypes[0]
}

func (x ReplicationGuaranteeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicationGuaranteeKind.Descriptor instead.
func (ReplicationGuaranteeKind) EnumDescriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{0}
}

type FilesystemVersion_VersionType int32

const (
	FilesystemVersion_Snapshot FilesystemVersion_VersionType = 0
	FilesystemVersion_Bookmark FilesystemVersion_VersionType = 1
)

// Enum value maps for FilesystemVersion_VersionType.
var (
	FilesystemVersion_VersionType_name = map[int32]string{
		0: "Snapshot",
		1: "Bookmark",
	}
	FilesystemVersion_VersionType_value = map[string]int32{
		"Snapshot": 0,
		"Bookmark": 1,
	}
)

func (x FilesystemVersion_VersionType) Enum() *FilesystemVersion_VersionType {
	p := new(FilesystemVersion_VersionType)
	*p = x
	return p
}

func (x FilesystemVersion_VersionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilesystemVersion_VersionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pdu_proto_enumTypes[1].Descriptor()
}

func (FilesystemVersion_VersionType) Type() protoreflect.EnumType {
	return &file_pdu_proto_enumTypes[1]
}

func (x FilesystemVersion_VersionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilesystemVersion_VersionType.Descriptor instead.
func (FilesystemVersion_VersionType) EnumDescriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{5, 0}
}

type ListFilesystemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesystemReq) Reset() {
	*x = ListFilesystemReq{}
	mi := &file_pdu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesystemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesystemReq) ProtoMessage() {}

func (x *ListFilesystemReq) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesystemReq.ProtoReflect.Descriptor instead.
func (*ListFilesystemReq) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{0}
}

type ListFilesystemRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filesystems   []*Filesystem          `protobuf:"bytes,1,rep,name=Filesystems,proto3" json:"Filesystems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesystemRes) Reset() {
	*x = ListFilesystemRes{}
	mi := &file_pdu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesystemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesystemRes) ProtoMessage() {}

func (x *ListFilesystemRes) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesystemRes.ProtoReflect.Descriptor instead.
func (*ListFilesystemRes) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{1}
}

func (x *ListFilesystemRes) GetFilesystems() []*Filesystem {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

type Filesystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	ResumeToken   string                 `protobuf:"bytes,2,opt,name=ResumeToken,proto3" json:"ResumeToken,omitempty"`
	IsPlaceholder bool                   `protobuf:"varint,3,opt,name=IsPlaceholder,proto3" json:"IsPlaceholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filesystem) Reset() {
	*x = Filesystem{}
	mi := &file_pdu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filesystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filesystem) ProtoMessage() {}

func (x *Filesystem) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filesystem.ProtoReflect.Descriptor instead.
func (*Filesystem) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{2}
}

func (x *Filesystem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Filesystem) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

func (x *Filesystem) GetIsPlaceholder() bool {
	if x != nil {
		return x.IsPlaceholder
	}
	return false
}

type ListFilesystemVersionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filesystem    string                 `protobuf:"bytes,1,opt,name=Filesystem,proto3" json:"Filesystem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesystemVersionsReq) Reset() {
	*x = ListFilesystemVersionsReq{}
	mi := &file_pdu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesystemVersionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesystemVersionsReq) ProtoMessage() {}

func (x *ListFilesystemVersionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesystemVersionsReq.ProtoReflect.Descriptor instead.
func (*ListFilesystemVersionsReq) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{3}
}

func (x *ListFilesystemVersionsReq) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

type ListFilesystemVersionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*FilesystemVersion   `protobuf:"bytes,1,rep,name=Versions,proto3" json:"Versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesystemVersionsRes) Reset() {
	*x = ListFilesystemVersionsRes{}
	mi := &file_pdu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesystemVersionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesystemVersionsRes) ProtoMessage() {}

func (x *ListFilesystemVersionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesystemVersionsRes.ProtoReflect.Descriptor instead.
func (*ListFilesystemVersionsRes) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{4}
}

func (x *ListFilesystemVersionsRes) GetVersions() []*FilesystemVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type FilesystemVersion struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Type          FilesystemVersion_VersionType `protobuf:"varint,1,opt,name=Type,proto3,enum=FilesystemVersion_VersionType" json:"Type,omitempty"`
	Name          string                        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Guid          uint64                        `protobuf:"varint,3,opt,name=Guid,proto3" json:"Guid,omitempty"`
	CreateTXG     uint64                        `protobuf:"varint,4,opt,name=CreateTXG,proto3" json:"CreateTXG,omitempty"`
	Creation      string                        `protobuf:"bytes,5,opt,name=Creation,proto3" json:"Creation,omitempty"` // RFC 3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemVersion) Reset() {
	*x = FilesystemVersion{}
	mi := &file_pdu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemVersion) ProtoMessage() {}

func (x *FilesystemVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemVersion.ProtoReflect.Descriptor instead.
func (*FilesystemVersion) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{5}
}

func (x *FilesystemVersion) GetType() FilesystemVersion_VersionType {
	if x != nil {
		return x.Type
	}
	return FilesystemVersion_Snapshot
}

func (x *FilesystemVersion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilesystemVersion) GetGuid() uint64 {
	if x != nil {
		return x.Guid
	}
	return 0
}

func (x *FilesystemVersion) GetCreateTXG() uint64 {
	if x != nil {
		return x.CreateTXG
	}
	return 0
}

func (x *FilesystemVersion) GetCreation() string {
	if x != nil {
		return x.Creation
	}
	return ""
}

type SendReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Filesystem string                 `protobuf:"bytes,1,opt,name=Filesystem,proto3" json:"Filesystem,omitempty"`
	// May be empty / null to request a full transfer of To
	From *FilesystemVersion `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To   *FilesystemVersion `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	// If ResumeToken is not empty, the resume token that CAN be used for 'zfs
	// send' by the sender. The sender MUST indicate use of ResumeToken in the
	// reply message SendRes.UsedResumeToken If it does not work, the sender
	// SHOULD clear the resume token on their side and use From and To instead If
	// ResumeToken is not empty, the GUIDs of From and To MUST correspond to those
	// encoded in the ResumeToken. Otherwise, the Sender MUST return an error.
	ResumeToken       string             `protobuf:"bytes,4,opt,name=ResumeToken,proto3" json:"ResumeToken,omitempty"`
	ReplicationConfig *ReplicationConfig `protobuf:"bytes,6,opt,name=ReplicationConfig,proto3" json:"ReplicationConfig,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendReq) Reset() {
	*x = SendReq{}
	mi := &file_pdu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReq) ProtoMessage() {}

func (x *SendReq) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReq.ProtoReflect.Descriptor instead.
func (*SendReq) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{6}
}

func (x *SendReq) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *SendReq) GetFrom() *FilesystemVersion {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SendReq) GetTo() *FilesystemVersion {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendReq) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

func (x *SendReq) GetReplicationConfig() *ReplicationConfig {
	if x != nil {
		return x.ReplicationConfig
	}
	return nil
}

type ReplicationConfig struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Protection    *ReplicationConfigProtection `protobuf:"bytes,1,opt,name=protection,proto3" json:"protection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationConfig) Reset() {
	*x = ReplicationConfig{}
	mi := &file_pdu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationConfig) ProtoMessage() {}

func (x *ReplicationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationConfig.ProtoReflect.Descriptor instead.
func (*ReplicationConfig) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{7}
}

func (x *ReplicationConfig) GetProtection() *ReplicationConfigProtection {
	if x != nil {
		return x.Protection
	}
	return nil
}

type ReplicationConfigProtection struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Initial       ReplicationGuaranteeKind `protobuf:"varint,1,opt,name=Initial,proto3,enum=ReplicationGuaranteeKind" json:"Initial,omitempty"`
	Incremental   ReplicationGuaranteeKind `protobuf:"varint,2,opt,name=Incremental,proto3,enum=ReplicationGuaranteeKind" json:"Incremental,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationConfigProtection) Reset() {
	*x = ReplicationConfigProtection{}
	mi := &file_pdu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationConfigProtection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationConfigProtection) ProtoMessage() {}

func (x *ReplicationConfigProtection) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationConfigProtection.ProtoReflect.Descriptor instead.
func (*ReplicationConfigProtection) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{8}
}

func (x *ReplicationConfigProtection) GetInitial() ReplicationGuaranteeKind {
	if x != nil {
		return x.Initial
	}
	return ReplicationGuaranteeKind_GuaranteeInvalid
}

func (x *ReplicationConfigProtection) GetIncremental() ReplicationGuaranteeKind {
	if x != nil {
		return x.Incremental
	}
	return ReplicationGuaranteeKind_GuaranteeInvalid
}

type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_pdu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{9}
}

func (x *Property) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Property) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SendRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the resume token provided in the request has been used or not.
	// If the SendReq.ResumeToken == "", this field MUST be false.
	UsedResumeToken bool `protobuf:"varint,1,opt,name=UsedResumeToken,proto3" json:"UsedResumeToken,omitempty"`
	// Expected stream size determined by dry run, not exact.
	// 0 indicates that for the given SendReq, no size estimate could be made.
	ExpectedSize  uint64 `protobuf:"varint,2,opt,name=ExpectedSize,proto3" json:"ExpectedSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRes) Reset() {
	*x = SendRes{}
	mi := &file_pdu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRes) ProtoMessage() {}

func (x *SendRes) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRes.ProtoReflect.Descriptor instead.
func (*SendRes) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{10}
}

func (x *SendRes) GetUsedResumeToken() bool {
	if x != nil {
		return x.UsedResumeToken
	}
	return false
}

func (x *SendRes) GetExpectedSize() uint64 {
	if x != nil {
		return x.ExpectedSize
	}
	return 0
}

type SendCompletedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalReq   *SendReq               `protobuf:"bytes,2,opt,name=OriginalReq,proto3" json:"OriginalReq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCompletedReq) Reset() {
	*x = SendCompletedReq{}
	mi := &file_pdu_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCompletedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCompletedReq) ProtoMessage() {}

func (x *SendCompletedReq) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCompletedReq.ProtoReflect.Descriptor instead.
func (*SendCompletedReq) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{11}
}

func (x *SendCompletedReq) GetOriginalReq() *SendReq {
	if x != nil {
		return x.OriginalReq
	}
	return nil
}

type SendCompletedRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCompletedRes) Reset() {
	*x = SendCompletedRes{}
	mi := &file_pdu_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCompletedRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCompletedRes) ProtoMessage() {}

func (x *SendCompletedRes) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCompletedRes.ProtoReflect.Descriptor instead.
func (*SendCompletedRes) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{12}
}

type ReceiveReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Filesystem string                 `protobuf:"bytes,1,opt,name=Filesystem,proto3" json:"Filesystem,omitempty"`
	To         *FilesystemVersion     `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	// If true, the receiver should clear the resume token before performing the
	// zfs recv of the stream in the request
	ClearResumeToken  bool               `protobuf:"varint,3,opt,name=ClearResumeToken,proto3" json:"ClearResumeToken,omitempty"`
	ReplicationConfig *ReplicationConfig `protobuf:"bytes,4,opt,name=ReplicationConfig,proto3" json:"ReplicationConfig,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReceiveReq) Reset() {
	*x = ReceiveReq{}
	mi := &file_pdu_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveReq) ProtoMessage() {}

func (x *ReceiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveReq.ProtoReflect.Descriptor instead.
func (*ReceiveReq) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{13}
}

func (x *ReceiveReq) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *ReceiveReq) GetTo() *FilesystemVersion {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ReceiveReq) GetClearResumeToken() bool {
	if x != nil {
		return x.ClearResumeToken
	}
	return false
}

func (x *ReceiveReq) GetReplicationConfig() *ReplicationConfig {
	if x != nil {
		return x.ReplicationConfig
	}
	return nil
}

type ReceiveRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRes) Reset() {
	*x = ReceiveRes{}
	mi := &file_pdu_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRes) ProtoMessage() {}

func (x *ReceiveRes) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRes.ProtoReflect.Descriptor instead.
func (*ReceiveRes) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{14}
}

type DestroySnapshotsReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Filesystem string                 `protobuf:"bytes,1,opt,name=Filesystem,proto3" json:"Filesystem,omitempty"`
	// Path to filesystem, snapshot or bookmark to be destroyed
	Snapshots     []*FilesystemVersion `protobuf:"bytes,2,rep,name=Snapshots,proto3" json:"Snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySnapshotsReq) Reset() {
	*x = DestroySnapshotsReq{}
	mi := &file_pdu_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySnapshotsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySnapshotsReq) ProtoMessage() {}

func (x *DestroySnapshotsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySnapshotsReq.ProtoReflect.Descriptor instead.
func (*DestroySnapshotsReq) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{15}
}

func (x *DestroySnapshotsReq) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *DestroySnapshotsReq) GetSnapshots() []*FilesystemVersion {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type DestroySnapshotRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *FilesystemVersion     `protobuf:"bytes,1,opt,name=Snapshot,proto3" json:"Snapshot,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySnapshotRes) Reset() {
	*x = DestroySnapshotRes{}
	mi := &file_pdu_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySnapshotRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySnapshotRes) ProtoMessage() {}

func (x *DestroySnapshotRes) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySnapshotRes.ProtoReflect.Descriptor instead.
func (*DestroySnapshotRes) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{16}
}

func (x *DestroySnapshotRes) GetSnapshot() *FilesystemVersion {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *DestroySnapshotRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DestroySnapshotsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DestroySnapshotRes  `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySnapshotsRes) Reset() {
	*x = DestroySnapshotsRes{}
	mi := &file_pdu_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySnapshotsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySnapshotsRes) ProtoMessage() {}

func (x *DestroySnapshotsRes) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySnapshotsRes.ProtoReflect.Descriptor instead.
func (*DestroySnapshotsRes) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{17}
}

func (x *DestroySnapshotsRes) GetResults() []*DestroySnapshotRes {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReplicationCursorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filesystem    string                 `protobuf:"bytes,1,opt,name=Filesystem,proto3" json:"Filesystem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationCursorReq) Reset() {
	*x = ReplicationCursorReq{}
	mi := &file_pdu_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationCursorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationCursorReq) ProtoMessage() {}

func (x *ReplicationCursorReq) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationCursorReq.ProtoReflect.Descriptor instead.
func (*ReplicationCursorReq) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{18}
}

func (x *ReplicationCursorReq) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

type ReplicationCursorRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ReplicationCursorRes_Guid
	//	*ReplicationCursorRes_Notexist
	Result        isReplicationCursorRes_Result `protobuf_oneof:"Result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationCursorRes) Reset() {
	*x = ReplicationCursorRes{}
	mi := &file_pdu_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationCursorRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationCursorRes) ProtoMessage() {}

func (x *ReplicationCursorRes) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationCursorRes.ProtoReflect.Descriptor instead.
func (*ReplicationCursorRes) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{19}
}

func (x *ReplicationCursorRes) GetResult() isReplicationCursorRes_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReplicationCursorRes) GetGuid() uint64 {
	if x != nil {
		if x, ok := x.Result.(*ReplicationCursorRes_Guid); ok {
			return x.Guid
		}
	}
	return 0
}

func (x *ReplicationCursorRes) GetNotexist() bool {
	if x != nil {
		if x, ok := x.Result.(*ReplicationCursorRes_Notexist); ok {
			return x.Notexist
		}
	}
	return false
}

type isReplicationCursorRes_Result interface {
	isReplicationCursorRes_Result()
}

type ReplicationCursorRes_Guid struct {
	Guid uint64 `protobuf:"varint,1,opt,name=Guid,proto3,oneof"`
}

type ReplicationCursorRes_Notexist struct {
	Notexist bool `protobuf:"varint,2,opt,name=Notexist,proto3,oneof"`
}

func (*ReplicationCursorRes_Guid) isReplicationCursorRes_Result() {}

func (*ReplicationCursorRes_Notexist) isReplicationCursorRes_Result() {}

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_pdu_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{20}
}

func (x *PingReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echo must be PingReq.Message
	Echo          string `protobuf:"bytes,1,opt,name=Echo,proto3" json:"Echo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRes) Reset() {
	*x = PingRes{}
	mi := &file_pdu_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRes) ProtoMessage() {}

func (x *PingRes) ProtoReflect() protoreflect.Message {
	mi := &file_pdu_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRes.ProtoReflect.Descriptor instead.
func (*PingRes) Descriptor() ([]byte, []int) {
	return file_pdu_proto_rawDescGZIP(), []int{21}
}

func (x *PingRes) GetEcho() string {
	if x != nil {
		return x.Echo
	}
	return ""
}

var File_pdu_proto protoreflect.FileDescriptor

const file_pdu_proto_rawDesc = "" +
	"\n" +
	"\tpdu.proto\"\x13\n" +
	"\x11ListFilesystemReq\"B\n" +
	"\x11ListFilesystemRes\x12-\n" +
	"\vFilesystems\x18\x01 \x03(\v2\v.FilesystemR\vFilesystems\"h\n" +
	"\n" +
	"Filesystem\x12\x12\n" +
	"\x04Path\x18\x01 \x01(\tR\x04Path\x12 \n" +
	"\vResumeToken\x18\x02 \x01(\tR\vResumeToken\x12$\n" +
	"\rIsPlaceholder\x18\x03 \x01(\bR\rIsPlaceholder\";\n" +
	"\x19ListFilesystemVersionsReq\x12\x1e\n" +
	"\n" +
	"Filesystem\x18\x01 \x01(\tR\n" +
	"Filesystem\"K\n" +
	"\x19ListFilesystemVersionsRes\x12.\n" +
	"\bVersions\x18\x01 \x03(\v2\x12.FilesystemVersionR\bVersions\"\xd4\x01\n" +
	"\x11FilesystemVersion\x122\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x1e.FilesystemVersion.VersionTypeR\x04Type\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Guid\x18\x03 \x01(\x04R\x04Guid\x12\x1c\n" +
	"\tCreateTXG\x18\x04 \x01(\x04R\tCreateTXG\x12\x1a\n" +
	"\bCreation\x18\x05 \x01(\tR\bCreation\")\n" +
	"\vVersionType\x12\f\n" +
	"\bSnapshot\x10\x00\x12\f\n" +
	"\bBookmark\x10\x01\"\xd9\x01\n" +
	"\aSendReq\x12\x1e\n" +
	"\n" +
	"Filesystem\x18\x01 \x01(\tR\n" +
	"Filesystem\x12&\n" +
	"\x04From\x18\x02 \x01(\v2\x12.FilesystemVersionR\x04From\x12\"\n" +
	"\x02To\x18\x03 \x01(\v2\x12.FilesystemVersionR\x02To\x12 \n" +
	"\vResumeToken\x18\x04 \x01(\tR\vResumeToken\x12@\n" +
	"\x11ReplicationConfig\x18\x06 \x01(\v2\x12.ReplicationConfigR\x11ReplicationConfig\"Q\n" +
	"\x11ReplicationConfig\x12<\n" +
	"\n" +
	"protection\x18\x01 \x01(\v2\x1c.ReplicationConfigProtectionR\n" +
	"protection\"\x8f\x01\n" +
	"\x1bReplicationConfigProtection\x123\n" +
	"\aInitial\x18\x01 \x01(\x0e2\x19.ReplicationGuaranteeKindR\aInitial\x12;\n" +
	"\vIncremental\x18\x02 \x01(\x0e2\x19.ReplicationGuaranteeKindR\vIncremental\"4\n" +
	"\bProperty\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"W\n" +
	"\aSendRes\x12(\n" +
	"\x0fUsedResumeToken\x18\x01 \x01(\bR\x0fUsedResumeToken\x12\"\n" +
	"\fExpectedSize\x18\x02 \x01(\x04R\fExpectedSize\">\n" +
	"\x10SendCompletedReq\x12*\n" +
	"\vOriginalReq\x18\x02 \x01(\v2\b.SendReqR\vOriginalReq\"\x12\n" +
	"\x10SendCompletedRes\"\xbe\x01\n" +
	"\n" +
	"ReceiveReq\x12\x1e\n" +
	"\n" +
	"Filesystem\x18\x01 \x01(\tR\n" +
	"Filesystem\x12\"\n" +
	"\x02To\x18\x02 \x01(\v2\x12.FilesystemVersionR\x02To\x12*\n" +
	"\x10ClearResumeToken\x18\x03 \x01(\bR\x10ClearResumeToken\x12@\n" +
	"\x11ReplicationConfig\x18\x04 \x01(\v2\x12.ReplicationConfigR\x11ReplicationConfig\"\f\n" +
	"\n" +
	"ReceiveRes\"g\n" +
	"\x13DestroySnapshotsReq\x12\x1e\n" +
	"\n" +
	"Filesystem\x18\x01 \x01(\tR\n" +
	"Filesystem\x120\n" +
	"\tSnapshots\x18\x02 \x03(\v2\x12.FilesystemVersionR\tSnapshots\"Z\n" +
	"\x12DestroySnapshotRes\x12.\n" +
	"\bSnapshot\x18\x01 \x01(\v2\x12.FilesystemVersionR\bSnapshot\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"D\n" +
	"\x13DestroySnapshotsRes\x12-\n" +
	"\aResults\x18\x01 \x03(\v2\x13.DestroySnapshotResR\aResults\"6\n" +
	"\x14ReplicationCursorReq\x12\x1e\n" +
	"\n" +
	"Filesystem\x18\x01 \x01(\tR\n" +
	"Filesystem\"T\n" +
	"\x14ReplicationCursorRes\x12\x14\n" +
	"\x04Guid\x18\x01 \x01(\x04H\x00R\x04Guid\x12\x1c\n" +
	"\bNotexist\x18\x02 \x01(\bH\x00R\bNotexistB\b\n" +
	"\x06Result\"#\n" +
	"\aPingReq\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\"\x1d\n" +
	"\aPingRes\x12\x12\n" +
	"\x04Echo\x18\x01 \x01(\tR\x04Echo*\x86\x01\n" +
	"\x18ReplicationGuaranteeKind\x12\x14\n" +
	"\x10GuaranteeInvalid\x10\x00\x12\x19\n" +
	"\x15GuaranteeResumability\x10\x01\x12#\n" +
	"\x1fGuaranteeIncrementalReplication\x10\x02\x12\x14\n" +
	"\x10GuaranteeNothing\x10\x032\x8f\x03\n" +
	"\vReplication\x12\x1a\n" +
	"\x04Ping\x12\b.PingReq\x1a\b.PingRes\x129\n" +
	"\x0fListFilesystems\x12\x12.ListFilesystemReq\x1a\x12.ListFilesystemRes\x12P\n" +
	"\x16ListFilesystemVersions\x12\x1a.ListFilesystemVersionsReq\x1a\x1a.ListFilesystemVersionsRes\x12>\n" +
	"\x10DestroySnapshots\x12\x14.DestroySnapshotsReq\x1a\x14.DestroySnapshotsRes\x12A\n" +
	"\x11ReplicationCursor\x12\x15.ReplicationCursorReq\x1a\x15.ReplicationCursorRes\x12\x1d\n" +
	"\aSendDry\x12\b.SendReq\x1a\b.SendRes\x125\n" +
	"\rSendCompleted\x12\x11.SendCompletedReq\x1a\x11.SendCompletedResB\aZ\x05.;pdub\x06proto3"

var (
	file_pdu_proto_rawDescOnce sync.Once
	file_pdu_proto_rawDescData []byte
)

func file_pdu_proto_rawDescGZIP() []byte {
	file_pdu_proto_rawDescOnce.Do(func() {
		file_pdu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pdu_proto_rawDesc), len(file_pdu_proto_rawDesc)))
	})
	return file_pdu_proto_rawDescData
}

var file_pdu_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pdu_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pdu_proto_goTypes = []any{
	(ReplicationGuaranteeKind)(0),       // 0: ReplicationGuaranteeKind
	(FilesystemVersion_VersionType)(0),  // 1: FilesystemVersion.VersionType
	(*ListFilesystemReq)(nil),           // 2: ListFilesystemReq
	(*ListFilesystemRes)(nil),           // 3: ListFilesystemRes
	(*Filesystem)(nil),                  // 4: Filesystem
	(*ListFilesystemVersionsReq)(nil),   // 5: ListFilesystemVersionsReq
	(*ListFilesystemVersionsRes)(nil),   // 6: ListFilesystemVersionsRes
	(*FilesystemVersion)(nil),           // 7: FilesystemVersion
	(*SendReq)(nil),                     // 8: SendReq
	(*ReplicationConfig)(nil),           // 9: ReplicationConfig
	(*ReplicationConfigProtection)(nil), // 10: ReplicationConfigProtection
	(*Property)(nil),                    // 11: Property
	(*SendRes)(nil),                     // 12: SendRes
	(*SendCompletedReq)(nil),            // 13: SendCompletedReq
	(*SendCompletedRes)(nil),            // 14: SendCompletedRes
	(*ReceiveReq)(nil),                  // 15: ReceiveReq
	(*ReceiveRes)(nil),                  // 16: ReceiveRes
	(*DestroySnapshotsReq)(nil),         // 17: DestroySnapshotsReq
	(*DestroySnapshotRes)(nil),          // 18: DestroySnapshotRes
	(*DestroySnapshotsRes)(nil),         // 19: DestroySnapshotsRes
	(*ReplicationCursorReq)(nil),        // 20: ReplicationCursorReq
	(*ReplicationCursorRes)(nil),        // 21: ReplicationCursorRes
	(*PingReq)(nil),                     // 22: PingReq
	(*PingRes)(nil),                     // 23: PingRes
}
var file_pdu_proto_depIdxs = []int32{
	4,  // 0: ListFilesystemRes.Filesystems:type_name -> Filesystem
	7,  // 1: ListFilesystemVersionsRes.Versions:type_name -> FilesystemVersion
	1,  // 2: FilesystemVersion.Type:type_name -> FilesystemVersion.VersionType
	7,  // 3: SendReq.From:type_name -> FilesystemVersion
	7,  // 4: SendReq.To:type_name -> FilesystemVersion
	9,  // 5: SendReq.ReplicationConfig:type_name -> ReplicationConfig
	10, // 6: ReplicationConfig.protection:type_name -> ReplicationConfigProtection
	0,  // 7: ReplicationConfigProtection.Initial:type_name -> ReplicationGuaranteeKind
	0,  // 8: ReplicationConfigProtection.Incremental:type_name -> ReplicationGuaranteeKind
	8,  // 9: SendCompletedReq.OriginalReq:type_name -> SendReq
	7,  // 10: ReceiveReq.To:type_name -> FilesystemVersion
	9,  // 11: ReceiveReq.ReplicationConfig:type_name -> ReplicationConfig
	7,  // 12: DestroySnapshotsReq.Snapshots:type_name -> FilesystemVersion
	7,  // 13: DestroySnapshotRes.Snapshot:type_name -> FilesystemVersion
	18, // 14: DestroySnapshotsRes.Results:type_name -> DestroySnapshotRes
	22, // 15: Replication.Ping:input_type -> PingReq
	2,  // 16: Replication.ListFilesystems:input_type -> ListFilesystemReq
	5,  // 17: Replication.ListFilesystemVersions:input_type -> ListFilesystemVersionsReq
	17, // 18: Replication.DestroySnapshots:input_type -> DestroySnapshotsReq
	20, // 19: Replication.ReplicationCursor:input_type -> ReplicationCursorReq
	8,  // 20: Replication.SendDry:input_type -> SendReq
	13, // 21: Replication.SendCompleted:input_type -> SendCompletedReq
	23, // 22: Replication.Ping:output_type -> PingRes
	3,  // 23: Replication.ListFilesystems:output_type -> ListFilesystemRes
	6,  // 24: Replication.ListFilesystemVersions:output_type -> ListFilesystemVersionsRes
	19, // 25: Replication.DestroySnapshots:output_type -> DestroySnapshotsRes
	21, // 26: Replication.ReplicationCursor:output_type -> ReplicationCursorRes
	12, // 27: Replication.SendDry:output_type -> SendRes
	14, // 28: Replication.SendCompleted:output_type -> SendCompletedRes
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pdu_proto_init() }
func file_pdu_proto_init() {
	if File_pdu_proto != nil {
		return
	}
	file_pdu_proto_msgTypes[19].OneofWrappers = []any{
		(*ReplicationCursorRes_Guid)(nil),
		(*ReplicationCursorRes_Notexist)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pdu_proto_rawDesc), len(file_pdu_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pdu_proto_goTypes,
		DependencyIndexes: file_pdu_proto_depIdxs,
		EnumInfos:         file_pdu_proto_enumTypes,
		MessageInfos:      file_pdu_proto_msgTypes,
	}.Build()
	File_pdu_proto = out.File
	file_pdu_proto_goTypes = nil
	file_pdu_proto_depIdxs = nil
}
