// Code generated by zrepl tooling; DO NOT EDIT.

package tests

var Cases = []Case{BatchDestroy,
	CreateReplicationCursor,
	GetNonexistent,
	IdempotentBookmark,
	IdempotentDestroy,
	IdempotentHold,
	ListFilesystemVersionsFilesystemNotExist,
	ListFilesystemVersionsTypeFilteringAndPrefix,
	ListFilesystemVersionsUserrefs,
	ListFilesystemVersionsZeroExistIsNotAnError,
	ListFilesystemsNoFilter,
	ResumableRecvAndTokenHandling,
	ResumeTokenParsing,
	SendArgsValidationEncryptedSendOfUnencryptedDatasetForbidden,
	SendArgsValidationResumeTokenDifferentFilesystemForbidden,
	SendArgsValidationResumeTokenEncryptionMismatchForbidden,
	UndestroyableSnapshotParsing,
}
