.. global list of substitutions

.. 
  .. |macroname| replace:: macro expansion

.. |GitHub license| image:: https://img.shields.io/github/license/zrepl/zrepl.svg
   :target: https://github.com/LyingCak3/zrepl/blob/master/LICENSE
.. |Language: Go| image:: https://img.shields.io/badge/lang-Go-6ad7e5.svg
   :target: https://golang.org/
.. |User Docs| image:: https://img.shields.io/badge/docs-web-blue.svg
   :target: https://zrepl.github.io


.. |serve-transport| replace:: :ref:`serve specification<transport>`
.. |connect-transport| replace:: :ref:`connect specification<transport>`
.. |send-options| replace:: :ref:`send options<job-send-options>`, e.g. for encrypted sends
.. |recv-options| replace:: :ref:`recv options<job-recv-options>`
.. |replication-options| replace:: :ref:`replication options<replication-options>`
.. |conflict-resolution-options| replace:: :ref:`conflict resolution options<conflict_resolution-options>`
.. |snapshotting-spec| replace:: :ref:`snapshotting specification <job-snapshotting-spec>`
.. |pruning-spec| replace:: :ref:`pruning specification <prune>`
.. |filter-spec| replace:: :ref:`filter specification<pattern-filter>`

.. |br| raw:: html

   <br/>