// Code generated by "stringer -type=ReplicationState"; DO NOT EDIT.

package replication

import "strconv"

const _ReplicationState_name = "PlanningPlanningErrorWorkingWorkingWaitCompletedContextDone"

var _ReplicationState_index = [...]uint8{0, 8, 21, 28, 39, 48, 59}

func (i ReplicationState) String() string {
	if i < 0 || i >= ReplicationState(len(_ReplicationState_index)-1) {
		return "ReplicationState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReplicationState_name[_ReplicationState_index[i]:_ReplicationState_index[i+1]]
}
